name: Test Workflow
on:
  workflow_dispatch:
  repository_dispatch:
    types: webhook
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run test.py
        run: python test.py